# Clojure CircleCI 2.0 configuration file for csv

version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run:
          name: Check formatting and lint code
          command: |
              lein cljfmt check
              lein with-profile test eastwood

      - run:
          name: Run tests
          command: lein test

      - run:
          name: Check and update test coverage
          command: |
              CLOVERAGE_VERSION=1.0.9 lein with-profile test cloverage --codecov
              bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
